// <auto-generated />
namespace WebStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserRoleAddressPhoneAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRoleAddressPhoneAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202403030807415_User-RoleAddressPhone-Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
